routes/web.php
Route::get('/notify-detail/{id}', [HomeController::class, 'notifyDetail'])->name('notifyDetail')->middleware('auth:company,student')->where('id', '[0-9]+');
Route::get('/posts', [HomeController::class, 'post'])->name('post');
Route::get('/post/{slug}', [HomeController::class, 'postDetail'])->name('postDetail');
Route::get('/postFAQ', [HomeController::class, 'postFAQ'])->name('postFAQ');
Route::get('/postCompany', [HomeController::class, 'postCompany'])->name('postCompany');

/*------------Ajax--------------*/
Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::put('/status', [AjaxController::class, 'status'])->name('status')->middleware('auth:manager,staff,company,student');
    Route::post('/recruitment', [AjaxController::class, 'recruitment'])->name('recruitment')->middleware('auth:company');
    Route::put('/recruitment', [AjaxController::class, 'statusRecruitment'])->name('recruitment.status')->middleware('auth:company,student');
    Route::post('/recruitment-detail', [AjaxController::class, 'getRecruitmentDetail'])->name('recruitment-detail')->middleware('auth:student');
    Route::post('/recruitment-pending', [AjaxController::class, 'getRecruitmentDetailPending'])->name('recruitment-pending')->middleware('auth:student');
    Route::get('/company', [AjaxController::class, 'getCompany'])->name('company')->middleware('auth:staff,student');
    Route::get('/student-reset-report', [AjaxController::class, 'getStudentPending'])->name('student.reset-report')->middleware('auth:staff,student');
    Route::post('/upload', [AjaxController::class, 'uploadFile'])->name('upload')->middleware('auth:manager,staff,company,student');
    Route::get('/student', [AjaxController::class, 'getStudent'])->name('student')->middleware('auth:company');
    Route::get('/service', [AjaxController::class, 'getReport'])->name('report')->middleware('auth:staff');
    Route::get('/cancel-report', [AjaxController::class, 'cancelReport'])->name('reportCancel')->middleware('auth:company');
    Route::get('/notifications', [AjaxController::class, 'notification'])->name('notification')->middleware('auth:staff,company,student');
    Route::post('/getnotification', [AjaxController::class, 'getOneNotification'])->name('getOneNotification')->middleware('auth:staff');
    Route::get('/watchedNotification', [AjaxController::class, 'watchedNotification'])->name('watchedNotification')->middleware('auth:staff,company,student');
    Route::post('/notify', [AjaxController::class, 'getNotify'])->name('notify')->middleware('auth:manager,staff');
    Route::post('/notification', [AjaxController::class, 'staffGetNotify'])->name('staffGetNotify')->middleware('auth:staff');
    Route::get('/checkTimeline/{type}', [Controller::class, 'checkTimeLine'])->name('checkTimeline')->middleware('auth:student');
    Route::get('/transcript',[AjaxController::class,'uploadTranscript'])->name('transcript')->middleware('auth:staff');
    Route::get('/request-cancle-student',[AjaxController::class,'requestCancleStudent'])->name('requestCancleStudent')->middleware('auth:student');
});

/*------------Social Login--------------*/
Route::get('/redirect/{provider}', [AuthenticationController::class, 'redirect'])->name('social.redirect');
Route::get('/callback/{provider}', [AuthenticationController::class, 'callback'])->name('social.callback');
Route::get('/email/verify/{guard}/{code}/{method}/{token}', [AuthenticationController::class, 'verified']);
/*------------Dashboard Route--------------*/
Route::prefix('admin')->name('admin.')->group(function () {
    Route::middleware(['guest:manager,staff', 'PreventBackHistory'])->group(function () {
        Route::view('/', 'auth.login');
        Route::view('/login', 'auth.login')->name('login');
        Route::view('/forgot', 'auth.forgotPassword')->name('forgot.show');
        Route::post('/forgot', [AuthenticationController::class, 'forgotPassword'])->name('forgot.send');
        Route::view('/confirm', 'auth.confirmMail')->name('confirm');
        Route::view('/change', 'auth.changePassword')->name('change.show');
        Route::post('/change', [AuthenticationController::class, 'changePassword'])->name('change.update');
        Route::post('/check', [AuthenticationController::class, 'check'])->name('check');
        Route::view('/lock-screen', 'auth.lockScreen')->name('lockScreen.index');
    });
    Route::middleware(['auth:manager,staff', 'PreventBackHistory'])->group(function () {
        Route::post('/lock-screen', [AuthenticationController::class, 'lockScreen'])->name('lockScreen');
    });
});
/*------------Manager Route--------------*/
Route::prefix('manager')->middleware(['auth:manager', 'PreventBackHistory'])->name('manager.')->group(function () {
    Route::get('/home', [HomeManagerController::class, 'index'])->name('home');
    Route::post('/logout', [AuthenticationController::class, 'logout'])->name('logout');
    Route::get('/profile', [AdminController::class, 'profile'])->name('profile');
    Route::get('/editProfile', [AdminController::class, 'editProfile'])->name('editProfile');
    Route::post('/updateProfile', [AdminController::class, 'updateProfile'])->name('updateProfile');
    //Todo MANAGER----->
    Route::resource('/staff', StaffController::class);
    Route::get('/import/staff', [StaffImportController::class,'index'])->name('import.staff.index');
    Route::post('/import/staff', [StaffImportController::class, 'store'])->name('import.staff.store');
    Route::resource('/timeline', TimelineController::class);
    Route::resource('/semester', SemesterController::class);
    Route::resource('/notify', NotifyController::class);
    Route::post('/notify/send/{id}', [NotifyController::class, 'sendNotify'])->name('sendNotify');
    Route::get('/userlog', [UserLogController::class, 'index'])->name('userlog');
    Route::get('/userlog/{id}', [UserLogController::class, 'getLogByUser'])->name('userlog.detail')->where('id', '[0-9]+');
});
/*------------Staff Route--------------*/
Route::prefix('staff')->middleware(['auth:staff', 'PreventBackHistory'])->name('staff.')->group(function () {

    Route::post('/logout', [AuthenticationController::class, 'logout'])->name('logout');
    Route::get('/profile', [AdminController::class, 'profile'])->name('profile');
    Route::get('/editProfile', [AdminController::class, 'editProfile'])->name('editProfile');
    Route::post('/updateProfile', [AdminController::class, 'updateProfile'])->name('updateProfile');
    //Todo STAFF----->
    Route::middleware(['isLogged'])->group(function () {
        //HOME
        Route::get('/home', [HomeStaffController::class, 'index'])->name('home');
        //Import File
        Route::post('/import-student', [StudentImportController::class, 'import'])->name('import.student');
        Route::get('/import-student', [StudentImportController::class,'index'])->name('import.student.show');
        //Student-manager
        Route::resource('/student', StudentController::class);
        Route::get('/student-report-detail/{id}', [StudentController::class, 'showReportDetail'])->name('student.showReportDetail')->where('id', '[0-9]+');
        Route::get('/student/{id}/sendMail', [StudentController::class, 'sendAccount'])->name('student.send')->where('id', '[0-9]+');
        Route::get('/student-service/{id}', [StudentController::class, 'studentSerivce'])->name('student.service')->where('id', '[0-9]+');
        //Company-manager
        Route::resource('/company', StaffCompanyController::class);
        Route::get('/pending-company', [StaffCompanyController::class, 'pendingCompany'])->name('company.pending');
        Route::post('/pending-company/{id}', [StaffCompanyController::class, 'approveCompany'])->name('company.approve')->where('id', '[0-9]+');

        Route::get('/staff-companys/{id}', [StaffCompanyController::class, 'showStaffCompany'])->name('staff-companys.show')->where('id', '[0-9]+');
        Route::get('/staff-company', [StaffCompanyController::class, 'createStaffCompany'])->name('staff-company.create');
        Route::post('/staff-company', [StaffCompanyController::class, 'storeStaffCompany'])->name('staff-company.store');
        Route::get('/staff-company/{id}', [StaffCompanyController::class, 'editStaffCompany'])->name('staff-company.edit')->where('id', '[0-9]+');
        Route::put('/staff-company/{id}', [StaffCompanyController::class, 'updateStaffCompany'])->name('staff-company.update')->where('id', '[0-9]+');
        Route::delete('/staff-company/{id}', [StaffCompanyController::class, 'destroyStaffCompany'])->name('staff-company.destroy')->where('id', '[0-9]+');

        Route::get('/post-companys/{id}', [StaffCompanyController::class, 'showPostCompany'])->name('post-companys.show')->where('id', '[0-9]+');
        Route::get('/post-company/{id}', [StaffCompanyController::class, 'editPostCompany'])->name('post-company.edit')->where('id', '[0-9]+');
        Route::put('/post-company/{id}', [StaffCompanyController::class, 'updatePostCompany'])->name('post-company.update')->where('id', '[0-9]+');
        Route::delete('/post-company/{id}', [StaffCompanyController::class, 'destroyPostCompany'])->name('post-company.destroy')->where('id', '[0-9]+');

        Route::get('/student-companys/{id}', [StaffCompanyController::class, 'showStudentCompany'])->name('student-companys.show')->where('id', '[0-9]+');
        Route::get('/student-company/{id}', [StaffCompanyController::class, 'editStudentCompany'])->name('student-company.edit')->where('id', '[0-9]+');
        Route::put('/student-company/{id}', [StaffCompanyController::class, 'updateStudentCompany'])->name('student-company.update')->where('id', '[0-9]+');
        Route::delete('/student-company/{id}', [StaffCompanyController::class, 'destroyStudentCompany'])->name('student-company.destroy')->where('id', '[0-9]+');
        //Other
        Route::resource('post-type', PostTypeController::class);
        Route::resource('post', PostController::class);

resources/views/dashboard/indexProfileAdmin.blade.php
@extends('layouts.dashboard')
@section('page-title', 'Thông tin tài khoản')
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="/admin">Tổng Quan</a></li>
                        <li class="breadcrumb-item active">Hồ sơ Cá Nhân</li>
                    </ol>
                </div>
                <h4 class="page-title">Hồ sơ Cá Nhân</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8" >
            <div class="card" >
                <div class="card-header card-header-icon card-header-primary d-flex justify-content-between">
                    <h4 class="card-title ">Hồ sơ cá nhân </h4>
                    <a href="{{Auth::guard('staff')->check() ?  route('staff.editProfile') : route('manager.editProfile')}}" class="font-italic">( Cập nhật )</a>
                </div>
                <div class="card-body">
                    <form autocomplete="off">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Họ và tên:</label>
                                    <input type="text" class="form-control" name="full_name"
                                           value="{{$user->profile->full_name}}" disabled>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Họ:</label>
                                    <input type="text" class="form-control" name="first_name"
                                           value="{{$user->profile->first_name}}" disabled>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Tên:</label>
                                    <input type="text" class="form-control" name="last_name"
                                           value="{{$user->profile->last_name}}" disabled>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Email:</label>
                                    <input type="name" class="form-control" name="name" disabled value="{{$user->email}}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Email cá nhân:</label>
                                    <input type="name" class="form-control" name="name" disabled value="{{$user->profile->email_personal}}">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Ngày sinh:</label>
                                    <input type="name" class="form-control" name="name" disabled value="{{date('d-m-Y',strtotime($user->profile->birthday)) }}">
                                </div>

                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Số điện thoại:</label>
                                    <input type="text" class="form-control" name="phone"
                                           value="{{$user->profile->phone}}" disabled>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label class="bmd-label-floating">CMND / CCCD:</label>
                                    <input type="text" class="form-control" name="indo"
                                           value="{{$user->profile->indo}}" disabled>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Giới tính:</label>
                                    <input type="name" class="form-control" name="name" disabled value="{{$user->profile->gender ? 'Nam' : 'Nữ' }}">
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Địa chỉ:</label>
                                    <input type="text" class="form-control" name="address"
                                           value="{{ $user->profile->address }}" disabled>
                                </div>
                            </div>
                        </div>
                        <div class="row mt-2 mb-4">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="{{ $user->profile->city_name }}" disabled>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="{{ $user->profile->district_name }}" disabled>

                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="{{ $user->profile->ward_name }}" disabled>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card" >
                <div class="card-header">
                    <h4 class="card-title"><i class="fas fa-image mr-1"></i> Hình Ảnh</h4>
                </div>

                <div class="card-body">

                    <h4 class="header-title m-t-0 m-b-30">Ảnh Đại Diện</h4>

                    <input type="file" class="dropify" data-default-file="assets/images/default-avatar.png" />
                    <h6 class="card-category text-primary mt-3"><i class="mdi mdi-shield-account">  </i> {{$user->role->name}} </h6>
                    <h3 class="font-weight-bold"> {{$user->name}} </h3>
                    <p class="text-primary">Email: {{$user->email}}</p>
                    <p class="card-description mt-3 font-italic">
                        {{!empty($user->profile->description) ? $user->profile->description : 'Chưa có thông tin tiểu sử' }}
                    </p>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('css')
    <!-- form Uploads -->
    <link href="assets/libs/fileuploads/css/dropify.min.css" rel="stylesheet" type="text/css" />
@endpush
@push('script')
    <!-- file uploads js -->
    <script src="assets/libs/fileuploads/js/dropify.min.js"></script>
    <script type="text/javascript">
        $('.dropify').dropify({
            messages: {
                'default': 'Kéo và thả tệp vào đây hoặc nhấp vào',
                'replace': 'Kéo và thả hoặc nhấp để thay thế',
                'remove': 'Thay đổi',
                'error': 'Rất tiếc, đã xảy ra sự cố.'
            },
            error: {
                'fileSize': 'Kích thước tệp quá lớn (tối đa 1M).'
            }
        });
        let urlImage = `{{$user->getAvatar()}}`
        if(urlImage) $(".dropify-render img").attr("src",urlImage) ;
    </script>

@endpush

resources/views/dashboard/updateProfileAdmin.blade.php
@extends('layouts.dashboard')
@section('page-title', 'Cập nhật hồ sơ')
@section('title', 'Cập nhật hồ sơ')
@section('content')
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="/admin">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Cập nhật hồ sơ</li>
                    </ol>
                </div>
                <h4 class="page-title">Cập Nhật Hồ Sơ</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->
    <!-- end row -->
    <form autocomplete="off" action="{{Auth::guard('staff')->check() ?  route('staff.updateProfile') :  route('manager.updateProfile')}}" method="POST" enctype="multipart/form-data">
        @csrf
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"><i class="far fa-address-card mr-1"></i> Hồ sơ cá nhân</h4>
                </div>
                <div class="row" style="width: 100%; height: 20px;"></div>
                <div class="card-body">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Họ và tên:</label>
                                    <input type="text" class="form-control" name="full_name" value="{{ !empty(old('full_name'))? old('full_name') : $user->profile->full_name}}">
                                    @error('full_name')
                                    <span class="text-danger small font-italic">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Biệt danh: <span class="font-weight-light">(nếu có)</span></label>
                                <input type="text" class="form-control" name="short_name" value="{{ !empty(old('short_name'))? old('short_name') : $user->profile->short_name}}" disabled>
                                @error('short_name')
                                <span class="text-danger small font-italic">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-5">
                            <div class="form-group ">
                                <label class="bmd-label-floating">Ngày Sinh:</label>
                                <input type="date" class="form-control" id="birthday" name="birthday" value="{{ date('Y-m-d', strtotime(!empty(old('birthday'))? old('birthday') : $user->profile->birthday)) }}">
                                @error('birthday')
                                <span class="text-danger small font-italic">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-3 pl-sm-3">
                            <div class="form-group">
                                <label class="">Giới Tính:</label>
                                <div class="d-flex flex-wrap">
                                    <div class="custom-control custom-radio  mr-2">
                                        <input type="radio" id="customRadio1" name="gender" value="{{MAN}}" class="custom-control-input" {{old('gender') == 0 || $user->profile->gender == 0 ? "checked" : ""}}>
                                        <label class="custom-control-label" for="customRadio1">Nam</label>
                                    </div>
                                    <div class="custom-control custom-radio">
                                        <input type="radio" id="customRadio2" name="gender" value="{{WOMEN}}" class="custom-control-input" {{old('gender') == 1 || $user->profile->gender == 1 ? "checked" : ""}}>
                                        <label class="custom-control-label" for="customRadio2">Nữ</label>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>

                    <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Email:</label>
                                    <input type="email" class="form-control"   value="{{$user->email}}" disabled>
                                </div>
                            </div>
                            <div class="col-md-6 ">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Email cá nhân: <span class="font-weight-light">(nếu có)</span></label>
                                    <input type="email" class="form-control"  name="email_personal" value="{{!empty(old('email_personal')) ?  old('email_personal') : $user->profile->email_personal}}">
                                    @error('email_personal')
                                    <span class="text-danger small font-italic">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Số điện thoại:</label>
                                    <input type="text" class="form-control" name="phone" value="{{!empty(old('phone'))? old('phone') : $user->profile->phone}}">
                                    @error('phone')
                                    <span class="text-danger small font-italic">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-8">
                                <div class="form-group">
                                    <label class="bmd-label-floating">CMND / CCCD:</label>
                                    <input type="text" class="form-control" name="indo" placeholder="Nhập số chứng minh thư của bạn" value="{{!empty(old('indo'))? old('indo') :$user->profile->indo}}">
                                    @error('indo')
                                    <span class="text-danger small font-italic">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Địa chỉ:</label>
                                    <input type="text" class="form-control" name="address" value="{{ !empty(old('address'))? old('address') : $user->profile->address }}">
                                </div>
                            </div>
                        </div>
                        @livewire('edit-address-admin',['cityCode' => !empty(old('city'))? old('city') : $user->profile->city_id,'districtCode' => !empty(old('district'))? old('district') : $user->profile->district_id,'wardsCode' => !empty(old('ward'))? old('ward') : $user->profile->ward_id ])
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Tiểu sử:</label>
                                    <div class="form-group">
                                        <textarea class="form-control" rows="5" name="description" > {{ !empty(old('description'))? old('description') : $user->profile->description }}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary pull-right">Cập nhật hồ sơ</button>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"><i class="fas fa-image mr-1"></i> Hình Ảnh</h4>
                </div>

                <div class="card-body">
                        <h4 class="header-title m-t-0 m-b-30">Ảnh Đại Diện</h4>
                    <input type="file" name="avatar" class="dropify" data-default-file="assets/images/default-avatar.png" />
                    <h6 class="card-category text-primary"><i class="mdi mdi-shield-account">  </i> {{$user->role->name}} </h6>
                    <h3 class="font-weight-bold"> {{$user->name}} </h3>
                    <p class="text-primary">Email: {{$user->email}}</p>
                    <p class="card-description mt-3 font-italic">
                        {{!empty($user->profile->description) ? $user->profile->description : 'Chưa có thông tin tiểu sử' }}
                    </p>
                </div>
            </div>
            <div class="card-box font-italic d-none d-sm-block">
                    <h4 class="header-title "><u>Chú ý:</u></h4>
                    <p class="card-description  ">
                        Mỗi nhân viên trong một doanh nghiệp, dù là làm toàn thời gian hay bán thời gian, ở vị trí nhân viên hay quản lý đều phải có trách nhiệm hoàn thành các nhiệm vụ cụ thể ở vị trí đó. Trách nhiệm của nhân viên là thực hiện các công việc được giao một cách tốt nhất trong khi tuân thủ các chính sách và giao thức của doanh nghiệp, quản lý thời gian và hoà nhập với văn hoá doanh nghiệp. Trong khi đó, quản lý đảm bảo cung cấp môi trường làm việc tích cực và sẵn sàng giải đáp các thắc mắc của nhân viên cấp dưới.
                    </p>
            </div>
        </div>
    </div>
    </form>

@endsection

@push('css')
    <!-- form Uploads -->
    <link href="assets/libs/fileuploads/css/dropify.min.css" rel="stylesheet" type="text/css" />
@endpush
@push('script')
    <!-- Script You Need -->
    <livewire:scripts />
    <!-- file uploads js -->
    <script src="assets/libs/fileuploads/js/dropify.min.js"></script>
    <script type="text/javascript">
        $('.dropify').dropify({
            messages: {
                'default': 'Kéo và thả tệp vào đây hoặc nhấp vào',
                'replace': 'Kéo và thả hoặc nhấp để thay thế',
                'remove': 'Thay đổi',
                'error': 'Rất tiếc, đã xảy ra sự cố.'
            },
            error: {
                'fileSize': 'Kích thước tệp quá lớn (tối đa 1M).'
            }
        });
        let urlImage = `{{$user->getAvatar()}}`
        if(urlImage) $(".dropify-render img").attr("src",urlImage) ;
    </script>

@endpush