routes/web.php
<?php

use App\Http\Controllers\Auth\AuthenticationController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AjaxController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Import\StaffImportController;
use App\Http\Controllers\Import\StudentImportController;
use App\Http\Controllers\Manager\StaffController;
use App\Http\Controllers\Manager\HomeController as HomeManagerController;
use App\Http\Controllers\Manager\NotifyController;
use App\Http\Controllers\Staff\NotifyController as  NotifyStaffController;
use App\Http\Controllers\Manager\SemesterController;
use App\Http\Controllers\Manager\TimelineController;
use App\Http\Controllers\Manager\UserLogController;
use App\Http\Controllers\Staff\StudentController;
use App\Http\Controllers\Staff\CompanyController as StaffCompanyController;
use App\Http\Controllers\Staff\CareersController;
use App\Http\Controllers\Staff\CareerGroupController;
use App\Http\Controllers\Staff\FeedBackController;
use App\Http\Controllers\Staff\HomeController as HomeStaffController;
use App\Http\Controllers\Staff\PostController;
use App\Http\Controllers\Staff\PostTypeController;
use App\Http\Controllers\Staff\RecruitmentController;
use App\Http\Controllers\Staff\WelfareController;
use App\Http\Controllers\Staff\ReportController;
use App\Http\Controllers\Student\HomeController as HomeStudentController;
use App\Http\Controllers\Student\ResumeController;
use App\Http\Controllers\Student\ReportController as StudentReportController;
use App\Http\Controllers\Student\ReportDetailController;
use App\Http\Controllers\Student\StudentController as StudentStudentController;
use App\Http\Controllers\Student\CompanyController as StudentCompanyController;
use App\Http\Controllers\Company\HomeController as HomeCompanyController;
use App\Http\Controllers\Company\UserController as UserCompanyController;
use App\Http\Controllers\Company\CompanyInformationController;
use App\Http\Controllers\Company\FeedBackController as CompanyFeedBackController;
use App\Http\Controllers\Company\RecruitmentDetailController;
use App\Http\Controllers\Company\RecruitmentPostController;
use App\Http\Controllers\Company\ReportRateController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Staff\ExemptionController;
use App\Http\Controllers\Staff\InternshipAgainController;
use App\Http\Controllers\Staff\RequestController;
use App\Http\Controllers\Staff\Transcript;
use App\Http\Controllers\Student\FeedbackController as StudentFeedbackController;
use App\Http\Controllers\Student\InternShipCancel;
use App\Http\Controllers\Student\ServiceExemptionController;
use App\Http\Controllers\Student\ServiceInternshipAgainController;
use App\Http\Controllers\Student\Transcript as StudentTranscript;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/error', function () {
    abort(404);
});
/*------------Home--------------*/
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/notify', [HomeController::class, 'notify'])->name('notify');
Route::view('/contact', 'clients.contact')->name('contact');
Route::view('/about', 'clients.about')->name('about');
Route::get('/recruitment/{slug}', [HomeController::class, 'recruitment'])->name('recruitment');
Route::get('/recruitment', [HomeController::class, 'recruitmentList'])->name('recruitment.list');
Route::any('/search-recruitment', [HomeController::class, 'searchRecruitment'])->name('search-recruitment.list');
Route::any('/list-career/{type}/{slug}', [HomeController::class, 'listCareerRecruitment'])->name('list-career');
Route::any('/list-city/{id}', [HomeController::class, 'listCityRecruitment'])->name('list-city');
Route::get('/company-infomation/{slug}', [HomeController::class, 'company'])->name('company.detail');
Route::post('/feed-back', [HomeController::class, 'feedBackStore'])->name('feed-back.store');
Route::get('/notify-detail/{id}', [HomeController::class, 'notifyDetail'])->name('notifyDetail')->middleware('auth:company,student')->where('id', '[0-9]+');
Route::get('/posts', [HomeController::class, 'post'])->name('post');
Route::get('/post/{slug}', [HomeController::class, 'postDetail'])->name('postDetail');
Route::get('/postFAQ', [HomeController::class, 'postFAQ'])->name('postFAQ');
Route::get('/postCompany', [HomeController::class, 'postCompany'])->name('postCompany');

/*------------Ajax--------------*/
Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::put('/status', [AjaxController::class, 'status'])->name('status')->middleware('auth:manager,staff,company,student');
    Route::post('/recruitment', [AjaxController::class, 'recruitment'])->name('recruitment')->middleware('auth:company');
    Route::put('/recruitment', [AjaxController::class, 'statusRecruitment'])->name('recruitment.status')->middleware('auth:company,student');
    Route::post('/recruitment-detail', [AjaxController::class, 'getRecruitmentDetail'])->name('recruitment-detail')->middleware('auth:student');
    Route::post('/recruitment-pending', [AjaxController::class, 'getRecruitmentDetailPending'])->name('recruitment-pending')->middleware('auth:student');
    Route::get('/company', [AjaxController::class, 'getCompany'])->name('company')->middleware('auth:staff,student');
    Route::get('/student-reset-report', [AjaxController::class, 'getStudentPending'])->name('student.reset-report')->middleware('auth:staff,student');
    Route::post('/upload', [AjaxController::class, 'uploadFile'])->name('upload')->middleware('auth:manager,staff,company,student');
    Route::get('/student', [AjaxController::class, 'getStudent'])->name('student')->middleware('auth:company');
    Route::get('/service', [AjaxController::class, 'getReport'])->name('report')->middleware('auth:staff');
    Route::get('/cancel-report', [AjaxController::class, 'cancelReport'])->name('reportCancel')->middleware('auth:company');
    Route::get('/notifications', [AjaxController::class, 'notification'])->name('notification')->middleware('auth:staff,company,student');
    Route::post('/getnotification', [AjaxController::class, 'getOneNotification'])->name('getOneNotification')->middleware('auth:staff');
    Route::get('/watchedNotification', [AjaxController::class, 'watchedNotification'])->name('watchedNotification')->middleware('auth:staff,company,student');
    Route::post('/notify', [AjaxController::class, 'getNotify'])->name('notify')->middleware('auth:manager,staff');
    Route::post('/notification', [AjaxController::class, 'staffGetNotify'])->name('staffGetNotify')->middleware('auth:staff');
    Route::get('/checkTimeline/{type}', [Controller::class, 'checkTimeLine'])->name('checkTimeline')->middleware('auth:student');
    Route::get('/transcript',[AjaxController::class,'uploadTranscript'])->name('transcript')->middleware('auth:staff');
    Route::get('/request-cancle-student',[AjaxController::class,'requestCancleStudent'])->name('requestCancleStudent')->middleware('auth:student');
});

/*------------Social Login--------------*/
Route::get('/redirect/{provider}', [AuthenticationController::class, 'redirect'])->name('social.redirect');
Route::get('/callback/{provider}', [AuthenticationController::class, 'callback'])->name('social.callback');
Route::get('/email/verify/{guard}/{code}/{method}/{token}', [AuthenticationController::class, 'verified']);
/*------------Dashboard Route--------------*/
Route::prefix('admin')->name('admin.')->group(function () {
    Route::middleware(['guest:manager,staff', 'PreventBackHistory'])->group(function () {
        Route::view('/', 'auth.login');
        Route::view('/login', 'auth.login')->name('login');
        Route::view('/forgot', 'auth.forgotPassword')->name('forgot.show');
        Route::post('/forgot', [AuthenticationController::class, 'forgotPassword'])->name('forgot.send');
        Route::view('/confirm', 'auth.confirmMail')->name('confirm');
        Route::view('/change', 'auth.changePassword')->name('change.show');
        Route::post('/change', [AuthenticationController::class, 'changePassword'])->name('change.update');
        Route::post('/check', [AuthenticationController::class, 'check'])->name('check');
        Route::view('/lock-screen', 'auth.lockScreen')->name('lockScreen.index');
    });
    Route::middleware(['auth:manager,staff', 'PreventBackHistory'])->group(function () {
        Route::post('/lock-screen', [AuthenticationController::class, 'lockScreen'])->name('lockScreen');
    });
});
/*------------Manager Route--------------*/
Route::prefix('manager')->middleware(['auth:manager', 'PreventBackHistory'])->name('manager.')->group(function () {
    Route::get('/home', [HomeManagerController::class, 'index'])->name('home');
    Route::post('/logout', [AuthenticationController::class, 'logout'])->name('logout');
    Route::get('/profile', [AdminController::class, 'profile'])->name('profile');
    Route::get('/editProfile', [AdminController::class, 'editProfile'])->name('editProfile');
    Route::post('/updateProfile', [AdminController::class, 'updateProfile'])->name('updateProfile');
    //Todo MANAGER----->
    Route::resource('/staff', StaffController::class);
    Route::get('/import/staff', [StaffImportController::class,'index'])->name('import.staff.index');
    Route::post('/import/staff', [StaffImportController::class, 'store'])->name('import.staff.store');
    Route::resource('/timeline', TimelineController::class);
    Route::resource('/semester', SemesterController::class);
    Route::resource('/notify', NotifyController::class);

app/Models/Welfare.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Welfare extends Model
{
    use HasFactory, SortDeleteHandle;

    protected $table = 'welfares';
    protected $primaryKey = 'id';

    protected $fillable = [
        'code',
        'name',
        'is_active',
        'deleted',
        'deleted_at',
        'deleted_by',
        'created_at',
        'created_by',
        'updated_by',
        'updated_at',
    ];
}

app/Http/Controllers/Manager/StaffController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Http\Requests\Manager\StaffCreateRequest;
use App\Http\Requests\Manager\StaffUpdateRequest;
use App\Models\City;
use App\Models\District;
use App\Models\ModelControllers\UserModel;
use App\Models\Profile;
use App\Models\User;
use App\Models\Ward;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class StaffController extends Controller
{
    public function index()
    {
        try {
            $user = User::where('role_id', STAFF_ROLE_ID)->get();
            return view('manager.staff.index', compact('user'));
        } catch (\Exception $ex) {
            abort(404);
        }
    }

    public function create()
    {
        try {
            return view('manager.staff.createUser');
        } catch (\Exception $ex) {
            abort(404);
        }
    }

    public function store(StaffCreateRequest $request)
    {
        try {
            $input = $request->all();
            $userModel = new UserModel();
            $userModel->upsertStaff($input);
            return redirect()->route('manager.staff.index')->with('success','Thêm nhân viên thành công');
        } catch (\Exception $ex) {
            abort(404);
        }
    }

    public function show($id)
    {
        try {
            $staff = User::find($id);
            $profile = $staff->profile;
            if ($staff && $profile) return view('manager.staff.detailUser', compact('staff', 'profile'));
            return redirect()->back()->withErrors('Tài khoản đang có sự cố!');
        } catch (\Exception $ex) {
            abort(404);
        }
    }

    public function edit($id)
    {

        try {
            $city = City::all();
            $district = District::all();
            $ward = Ward::all();
            $user = User::find($id);
            if ($user->is_logged) {
                return redirect()->back()->withErrors(['error' => 'Tài khoản đã được kích hoạt hệ thống']);
            }
            return view('manager.staff.editUser', compact('user','city', 'district', 'ward'));
        } catch (\Exception $ex) {
            abort(404);
        }
    }

    public function update(StaffUpdateRequest $request, $id)
    {
        try {
            $input = $request->all();
            $input['id'] = $id;
            DB::beginTransaction();
            $userModel = new UserModel();
            $userModel->upsertStaff($input, true);
            DB::commit();
            return redirect()->route('manager.staff.index')->with('success','Chỉnh nhân viên thành công');
        } catch (\Exception $ex) {
            DB::rollback();
            abort(404);
        }
    }

    public function destroy($id)
    {
        try {
            DB::beginTransaction();
            $staff = User::find($id);
            $profile=Profile::where('user_id',$staff->id)->first();
            $profile->delete();
            $staff->delete();
            DB::commit();
            return redirect()->route('manager.staff.index')->with('warning','Xóa nhân viên thành công');
        } catch (\Exception $ex) {
            DB::rollBack();
            abort(404);
        }
    }
}

app/Http/Controllers/Staff/CareerGroupController.php
<?php

namespace App\Http\Controllers\Staff;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\CareerGroup;
use App\Models\ModelControllers\CareerGroupModel;
use App\Http\Requests\Staff\CareerGroupRequest;
use App\Http\Requests\Staff\CareerGroupUpdateRequest;
use Illuminate\Support\Str;
use App\Supports\Log;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class CareerGroupController extends Controller
{
    public function index()
    {
        try {
            $careerGroup = CareerGroup::all();
        } catch (\Exception $ex) {
          abort(404);
        }

        return view('staff.careerGroup.index', compact('careerGroup'));

    }

    public function create()
    {
        try {
            return view('staff.careerGroup.createCareerGroup');
        } catch (\Exception $ex) {
            DB::rollBack();
            abort(404);
        }
     
    }

    public function store(CareerGroupRequest $request)
    {
        $input=$request->all();
        try {
            $careerGroupModel = new CareerGroupModel;
            $newData = $careerGroupModel->upsertCareerGroup($input);
            $newData['_method'] =$request->method();
            Log::save('Nhóm Ngành',$request->method(),null,$newData);
        } catch (\Exception $ex) {
          abort(404);
        }
        return redirect()->route('staff.careerGroup.index')->with('success','Đã Thêm Thành Công');
    }
    public function edit($id)
    {
        $careerGroup = CareerGroup::find($id);
        return view('staff.careerGroup.editCareerGroup', compact('careerGroup'));
    }
    public function update(CareerGroupUpdateRequest $request, $id)
    {
        $input = $request->all();
        $input['id'] = $id;
        try {
            $oldData=CareerGroup::find($id);
            $careerGroupModel = new CareerGroupModel();
            $newData = $careerGroupModel->upsertCareerGroup($input,true);
            Log::save('Nhóm Ngành',$request->method(),$oldData,$newData);
            return redirect()->route('staff.careerGroup.index')->with('success','Đã Sửa Thành Công');
        } catch (\Exception $ex) {
          abort(404);
        }
    }
    public function destroy($id)
    {
        try {
            $careerGroup = CareerGroup::find($id);
            Log::save('Nhóm Ngành','DELETE',null,$careerGroup,null);
            $careerGroup->delete();
            return redirect()->route('staff.careerGroup.index')->with('warning','Xóa thành công');
        } catch (\Exception $ex) {
          abort(404);
        };
    }
}

app/Http/Controllers/Staff/ReportRateController.php
<?php

namespace App\Http\Controllers\Staff;

use App\Http\Controllers\Controller;
use App\Models\Report;
use Illuminate\Http\Request;

class ReportRateController extends Controller
{
    public function showReport()
    {
        
    }

    public function detailReport($id)
    {
       
    }

    public function updateReportRate(Request $request, $id)
    {
       
    }
}

resources/views/staff/welfare/createWelfare.blade.php
@extends('layouts.dashboard')
@section('page-title', 'Quản lý Phúc Lợi | Tạo mới')
@section('title', 'Thêm Phúc Lợi')
@section('content')
@if(session()->has('status'))
<div class="col-sm-6 ml-3 alert alert-success">
    {{ session()->get('status') }}
</div>
@endif
<div class="content">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card ">
                        <div class="card-header card-header-icon card-header-rose">
                            <div class="card-icon">
                                <i class="material-icons">assignment</i>
                            </div>
                            <h4 class="card-title ">Thêm Phúc Lợi</h4>

                        </div>
                        <div class="card-body ">
                            <form method="POST" onsubmit="getLoading()" action="{{route('staff.welfare.store')}}" class="form-horizontal">
                                @csrf
                                @method('POST')
                                <div class="row">
                                    <label class="col-sm-2 col-form-label">Mã Phúc Lợi</label>
                                    <div class="col-sm-10">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="code" value="{{ old('code') }}">
                                            @error('code')
                                            <span class="text-danger small font-italic">{{ $message }}</span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <label class="col-sm-2 col-form-label">Tên Phúc Lợi</label>
                                    <div class="col-sm-10">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                                            @error('name')
                                            <span class="text-danger small font-italic">{{ $message }}</span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer ml-auto mr-auto">
                                    <button type="submit" class="btn btn-rose">Tạo Phúc Lợi</button>
                                </div>
                            </form>
                        </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endsection

@section('script')

@endsection

resources/views/staff/welfare/editWelfare.blade.php
@extends('layouts.dashboard')
@section('page-title', 'Quản lý Phúc Lợi | Tạo mới')
@section('title', 'Chỉnh Phúc Lợi')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="/admin">Tổng Quan</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('staff.post.index') }}">Danh sách phúc lợi</a></li>
                    <li class="breadcrumb-item active">Chỉnh sửa phúc lợi</li>
                </ol>
            </div>
            <h4 class="page-title">Chỉnh sửa phúc lợi</h4>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card-box">
            <form method="POST" onsubmit="getLoading()" action="{{route('staff.welfare.update',[$welfares->id])}}" class="form-horizontal">
                @csrf
                @method('PUT')
                <div class="row">
                    <label class="col-sm-2 col-form-label">Mã Phúc Lợi</label>
                    <div class="col-sm-10">
                        <div class="form-group">
                            <input type="text" class="form-control" name="code" value="{{$welfares->code}}">
                            @error('code')
                            <span class="text-danger small font-italic">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label">Tên Phúc Lợi</label>
                    <div class="col-sm-10">
                        <div class="form-group">
                            <input type="text" class="form-control" name="name" value="{{$welfares->name}}">
                            @error('name')
                            <span class="text-danger small font-italic">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
             
                    <button type="reset" class="btn btn-outline-info"><i class="fe-refresh-cw mr-1"></i> Làm
                        mới</button>
                    <button type="submit" class="btn btn-success"><i class="fa fa-save mr-1"></i> Lưu</button>
             
            </form>
        </div>
    </div>
</div>
@endsection

@section('script')

@endsection

resources/views/staff/welfare/index.blade.php
@extends('layouts.dashboard')
@section('page-title', 'Quản lý Phúc Lợi | Admin')
@section('title', 'Phúc Lợi')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="/admin">Tổng Quan</a></li>
                    <li class="breadcrumb-item active">Danh sách phúc lợi</li>
                </ol>
            </div>
            <h4 class="page-title">Danh sách phúc lợi</h4>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card-box">
            <form method="POST" onsubmit="getLoading()" action="{{route('staff.welfare.store')}}" class="form-horizontal">
                @csrf
                @method('POST')
                <div class="row">
                    <label class="col-sm-2 col-form-label">Mã Phúc Lợi</label>
                    <div class="col-sm-10">
                        <div class="form-group">
                            <input type="text" class="form-control" name="code" value="{{ old('code') }}">
                            @error('code')
                            <span class="text-danger small font-italic">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label">Tên Phúc Lợi</label>
                    <div class="col-sm-10">
                        <div class="form-group">
                            <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                            @error('name')
                            <span class="text-danger small font-italic">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary" type="submit">Thêm</button>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card-box">
            <div class="">
                <table class="table table-striped table-bordered dt-responsive nowrap dataTable no-footer dtr-inline" id="datatable">
                    <thead class="text-primary">
                        <tr>
                            <th class="text-center">Mã</th>
                            <th class="text-center">Tên Phúc Lợi</th>
                            <th class="text-center">Trạng Thái</th>
                            <th class="text-center">Chức Năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($welfares as $key => $row)
                        <tr>
                            <td class="text-center">{{ $row->code }}</td>
                            <td class="text-center">{{ Str::limit($row->name, 80) }}</td>
                            <td class="text-center">
                                <div class="togglebutton">
                                    <label>
                                        <input type="checkbox" @if ($row->is_active) checked @endif>
                                        <span class="toggle" onclick="isActive('{{ $row->id }}','WELFARE')"></span>
                                    </label>
                                </div>
                            </td>
                            <td class="text-center">
                                <a href="{{ route('staff.welfare.edit', $row->id) }}" class="btn btn-outline-primary"><i class="fas fa-pencil-alt"></i></a>
                                <a href="javascript: document.getElementById('deletedRow{{ $row->id }}').submit();" onclick="return confirm('Bạn Có muốn xóa???');" class="btn btn-outline-secondary"><i class="fas fa-trash"></i></a>
                                <form action="{{ route('staff.welfare.destroy', $row->id) }}" method="POST" id="deletedRow{{ $row->id }}" class="d-none">
                                    @method('DELETE')
                                    @csrf
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@push('css')
<!-- third party css -->
<link href="assets/libs/datatables/dataTables.bootstrap4.css" rel="stylesheet" type="text/css" />
<link href="assets/libs/datatables/buttons.bootstrap4.css" rel="stylesheet" type="text/css" />
<link href="assets/libs/datatables/responsive.bootstrap4.css" rel="stylesheet" type="text/css" />
<link href="assets/libs/switchery/switchery.min.css" rel="stylesheet" type="text/css" />
@endpush

@push('script')
<script src="assets/libs/datatables/jquery.dataTables.min.js"></script>
<script src="assets/libs/datatables/dataTables.bootstrap4.min.js"></script>
<script src="assets/libs/switchery/switchery.min.js"></script>
<!-- Buttons examples -->
<script src="assets/libs/datatables/dataTables.buttons.min.js"></script>
<script src="assets/libs/datatables/buttons.bootstrap4.min.js"></script>
<script src="assets/libs/jszip/jszip.min.js"></script>
<script src="assets/libs/pdfmake/pdfmake.min.js"></script>
<script src="assets/libs/pdfmake/vfs_fonts.js"></script>
<script src="assets/libs/datatables/buttons.html5.min.js"></script>
<script src="assets/libs/datatables/buttons.print.min.js"></script> b
<!-- Responsive examples -->
<script src="assets/libs/datatables/dataTables.responsive.min.js"></script>
<script src="assets/libs/datatables/responsive.bootstrap4.min.js"></script>
<script src="/assets/js/plugins/sweetalert2.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#datatable').DataTable({
            'aoColumnDefs': [{
                'bSortable': false,
                'aTargets': [-1]
            }],
            lengthChange: !1,
            buttons: ["copy", "excel"]
        }).buttons().container().appendTo("#datatable1_wrapper .col-md-6:eq(0)");
    });

    function isActive(id, model) {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $.ajax({
            url: `{{ route('ajax.status') }}`,
            type: 'PUT',
            dataType: 'json',
            data: {
                _token: '{{ csrf_token() }}',
                id: id,
                model: model,
            },
            success: function(response) {
                if (response)
                    swal({
                        title: "Cho phép hoạt động!",
                        text: "Bạn đã vừa thay đổi trạng thái hoạt động!",
                        buttonsStyling: false,
                        confirmButtonClass: "btn btn-success",
                        type: "success"
                    }).catch(swal.noop)
                else {
                    swal({
                        title: "Đã tắt hoạt động!",
                        text: "Bạn đã vừa thay đổi trạng thái hoạt động!",
                        icon: 'error',
                        buttonsStyling: false,
                        confirmButtonClass: "btn btn-warning",
                        type: 'warning',
                    }).catch(swal.noop)
                }
                // showNotification ('top','center','success', 'Thay đổi trạng thái thành công!',1000);
            },
            error: function(response) {
                swal({
                    title: "Lỗi hệ thống!",
                    text: "Đã xảy ra sự cố vui lòng thử lại sau!",
                    icon: 'error',
                    buttonsStyling: false,
                    confirmButtonClass: "btn btn-danger",
                    type: 'error',
                }).catch(swal.noop)
            }
        });
    }
</script>
@endpush