routes/web.php
<?php

use App\Http\Controllers\Auth\AuthenticationController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AjaxController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Import\StaffImportController;
use App\Http\Controllers\Import\StudentImportController;
use App\Http\Controllers\Manager\StaffController;
use App\Http\Controllers\Manager\HomeController as HomeManagerController;
use App\Http\Controllers\Manager\NotifyController;
use App\Http\Controllers\Staff\NotifyController as  NotifyStaffController;
use App\Http\Controllers\Manager\SemesterController;
use App\Http\Controllers\Manager\TimelineController;
use App\Http\Controllers\Manager\UserLogController;
use App\Http\Controllers\Staff\StudentController;
use App\Http\Controllers\Staff\CompanyController as StaffCompanyController;
use App\Http\Controllers\Staff\CareersController;
use App\Http\Controllers\Staff\CareerGroupController;
use App\Http\Controllers\Staff\FeedBackController;
use App\Http\Controllers\Staff\HomeController as HomeStaffController;
use App\Http\Controllers\Staff\PostController;
use App\Http\Controllers\Staff\PostTypeController;
use App\Http\Controllers\Staff\RecruitmentController;
use App\Http\Controllers\Staff\WelfareController;
use App\Http\Controllers\Staff\ReportController;
use App\Http\Controllers\Student\HomeController as HomeStudentController;
use App\Http\Controllers\Student\ResumeController;
use App\Http\Controllers\Student\ReportController as StudentReportController;
use App\Http\Controllers\Student\ReportDetailController;
use App\Http\Controllers\Student\StudentController as StudentStudentController;
use App\Http\Controllers\Student\CompanyController as StudentCompanyController;
use App\Http\Controllers\Company\HomeController as HomeCompanyController;
use App\Http\Controllers\Company\UserController as UserCompanyController;
use App\Http\Controllers\Company\CompanyInformationController;
use App\Http\Controllers\Company\FeedBackController as CompanyFeedBackController;
use App\Http\Controllers\Company\RecruitmentDetailController;
use App\Http\Controllers\Company\RecruitmentPostController;
use App\Http\Controllers\Company\ReportRateController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Staff\ExemptionController;
use App\Http\Controllers\Staff\InternshipAgainController;
use App\Http\Controllers\Staff\RequestController;
use App\Http\Controllers\Staff\Transcript;
use App\Http\Controllers\Student\FeedbackController as StudentFeedbackController;
use App\Http\Controllers\Student\InternShipCancel;
use App\Http\Controllers\Student\ServiceExemptionController;
use App\Http\Controllers\Student\ServiceInternshipAgainController;
use App\Http\Controllers\Student\Transcript as StudentTranscript;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/error', function () {
    abort(404);
});
/*------------Home--------------*/
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/notify', [HomeController::class, 'notify'])->name('notify');
Route::view('/contact', 'clients.contact')->name('contact');
Route::view('/about', 'clients.about')->name('about');
Route::get('/recruitment/{slug}', [HomeController::class, 'recruitment'])->name('recruitment');
Route::get('/recruitment', [HomeController::class, 'recruitmentList'])->name('recruitment.list');
Route::any('/search-recruitment', [HomeController::class, 'searchRecruitment'])->name('search-recruitment.list');
Route::any('/list-career/{type}/{slug}', [HomeController::class, 'listCareerRecruitment'])->name('list-career');
Route::any('/list-city/{id}', [HomeController::class, 'listCityRecruitment'])->name('list-city');
Route::get('/company-infomation/{slug}', [HomeController::class, 'company'])->name('company.detail');
Route::post('/feed-back', [HomeController::class, 'feedBackStore'])->name('feed-back.store');
Route::get('/notify-detail/{id}', [HomeController::class, 'notifyDetail'])->name('notifyDetail')->middleware('auth:company,student')->where('id', '[0-9]+');
Route::get('/posts', [HomeController::class, 'post'])->name('post');
Route::get('/post/{slug}', [HomeController::class, 'postDetail'])->name('postDetail');
Route::get('/postFAQ', [HomeController::class, 'postFAQ'])->name('postFAQ');
Route::get('/postCompany', [HomeController::class, 'postCompany'])->name('postCompany');

/*------------Ajax--------------*/
Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::put('/status', [AjaxController::class, 'status'])->name('status')->middleware('auth:manager,staff,company,student');
    Route::post('/recruitment', [AjaxController::class, 'recruitment'])->name('recruitment')->middleware('auth:company');
    Route::put('/recruitment', [AjaxController::class, 'statusRecruitment'])->name('recruitment.status')->middleware('auth:company,student');
    Route::post('/recruitment-detail', [AjaxController::class, 'getRecruitmentDetail'])->name('recruitment-detail')->middleware('auth:student');
    Route::post('/recruitment-pending', [AjaxController::class, 'getRecruitmentDetailPending'])->name('recruitment-pending')->middleware('auth:student');
    Route::get('/company', [AjaxController::class, 'getCompany'])->name('company')->middleware('auth:staff,student');
    Route::get('/student-reset-report', [AjaxController::class, 'getStudentPending'])->name('student.reset-report')->middleware('auth:staff,student');
    Route::post('/upload', [AjaxController::class, 'uploadFile'])->name('upload')->middleware('auth:manager,staff,company,student');
    Route::get('/student', [AjaxController::class, 'getStudent'])->name('student')->middleware('auth:company');
    Route::get('/service', [AjaxController::class, 'getReport'])->name('report')->middleware('auth:staff');
    Route::get('/cancel-report', [AjaxController::class, 'cancelReport'])->name('reportCancel')->middleware('auth:company');
    Route::get('/notifications', [AjaxController::class, 'notification'])->name('notification')->middleware('auth:staff,company,student');
    Route::post('/getnotification', [AjaxController::class, 'getOneNotification'])->name('getOneNotification')->middleware('auth:staff');
    Route::get('/watchedNotification', [AjaxController::class, 'watchedNotification'])->name('watchedNotification')->middleware('auth:staff,company,student');
    Route::post('/notify', [AjaxController::class, 'getNotify'])->name('notify')->middleware('auth:manager,staff');
    Route::post('/notification', [AjaxController::class, 'staffGetNotify'])->name('staffGetNotify')->middleware('auth:staff');
    Route::get('/checkTimeline/{type}', [Controller::class, 'checkTimeLine'])->name('checkTimeline')->middleware('auth:student');
    Route::get('/transcript',[AjaxController::class,'uploadTranscript'])->name('transcript')->middleware('auth:staff');
    Route::get('/request-cancle-student',[AjaxController::class,'requestCancleStudent'])->name('requestCancleStudent')->middleware('auth:student');
});

/*------------Social Login--------------*/
Route::get('/redirect/{provider}', [AuthenticationController::class, 'redirect'])->name('social.redirect');
Route::get('/callback/{provider}', [AuthenticationController::class, 'callback'])->name('social.callback');
Route::get('/email/verify/{guard}/{code}/{method}/{token}', [AuthenticationController::class, 'verified']);
/*------------Dashboard Route--------------*/
Route::prefix('admin')->name('admin.')->group(function () {
    Route::middleware(['guest:manager,staff', 'PreventBackHistory'])->group(function () {
        Route::view('/', 'auth.login');
        Route::view('/login', 'auth.login')->name('login');
        Route::view('/forgot', 'auth.forgotPassword')->name('forgot.show');
        Route::post('/forgot', [AuthenticationController::class, 'forgotPassword'])->name('forgot.send');
        Route::view('/confirm', 'auth.confirmMail')->name('confirm');
        Route::view('/change', 'auth.changePassword')->name('change.show');
        Route::post('/change', [AuthenticationController::class, 'changePassword'])->name('change.update');
        Route::post('/check', [AuthenticationController::class, 'check'])->name('check');
        Route::view('/lock-screen', 'auth.lockScreen')->name('lockScreen.index');
    });
    Route::middleware(['auth:manager,staff', 'PreventBackHistory'])->group(function () {
        Route::post('/lock-screen', [AuthenticationController::class, 'lockScreen'])->name('lockScreen');
    });
});
/*------------Manager Route--------------*/
Route::prefix('manager')->middleware(['auth:manager', 'PreventBackHistory'])->name('manager.')->group(function () {
    Route::get('/home', [HomeManagerController::class, 'index'])->name('home');
    Route::post('/logout', [AuthenticationController::class, 'logout'])->name('logout');
    Route::get('/profile', [AdminController::class, 'profile'])->name('profile');
    Route::get('/editProfile', [AdminController::class, 'editProfile'])->name('editProfile');
    Route::post('/updateProfile', [AdminController::class, 'updateProfile'])->name('updateProfile');
    //Todo MANAGER----->
    Route::resource('/staff', StaffController::class);
    Route::get('/import/staff', [StaffImportController::class,'index'])->name('import.staff.index');
    Route::post('/import/staff', [StaffImportController::class, 'store'])->name('import.staff.store');
    Route::resource('/timeline', TimelineController::class);
    Route::resource('/semester', SemesterController::class);
    Route::resource('/notify', NotifyController::class);

app/Models/Semester.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Semester extends Model
{
    use HasFactory, SortDeleteHandle;

    protected $table = 'semesters';
    protected $primaryKey = 'id';

    protected $fillable = [
        'code',
        'name',
        'from',
        'to',
        'is_current',
        'description',
        'deleted',
        'deleted_at',
        'deleted_by',
        'created_at',
        'created_by',
        'updated_by',
        'updated_at',
    ];
    public function timeline()
    {
        return $this->belongsTo(Timeline::class,'id','semester_id');
    }
}

app/Http/Controllers/Manager/HomeController.php
<?php


namespace App\Http\Controllers\Manager;

use App\Models\Company;
use App\Models\Notify;
use App\Models\Semester;
use App\Models\Timeline;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Session;

class HomeController
{
    public function index()
    {
       try{
            $staff = User::where('role_id',STAFF_ROLE_ID)->count();
            $company = User::whereHas('company', function ($query) {
                $query->where('is_active', 1)->where('on_system', 1);
            })->count();
            $student= User::where('role_id',STUDENT_ROLE_ID)->count();
            $timelines = Timeline::with('semester')->get();
            $notify =Notify::all()->count();
           $companyTopRecruitment = Company::withCount('recruitmentPostDetails')->with('recruitmentPostDetails')
               ->orderBy('recruitment_post_details_count', 'DESC')->limit(15)->get();
//            $companyTopRecruitment = Company::withCount('reports')->with('reports')->whereHas('reports',function($query){
//                $query->whereNotNull('company_id')->where('is_active',1);
//            })->orderBy('reports_count','desc')->get();
            // dd($companyTopRecruitment);

            $countPendingStudents = User::with('reports')
            ->whereHas('reports', function ($query) {
                $query->where('status', 'PENDING')->where('is_active', 1);
            })
            ->get();
        $countPassStudents = User::withCount('reports')->with('reports')
            ->whereHas('reports', function ($query) {
                $query->where('status', 'PASS')->where('is_active', 1);
            })
            ->get();
        $countFailStudents = User::withCount('reports')->with('reports')
            ->whereHas('reports', function ($query) {
                $query->where('status', 'FAIL')->where('is_active', 1);
            })
            ->get();
            $countDoneStudents = User::withCount('reports')->with('reports')
            ->whereHas('reports', function ($query) {
                $query->where('status', 'DONE')->where('is_active', 1);
            })
            ->get();
            $countCancelStudents = User::withCount('reports')->with('reports')
            ->whereHas('reports', function ($query) {
                $query->where('status', 'CANCEL')->where('is_active', 1);
            })
            ->get();
            return view('manager.home',compact('staff','company','student','notify','timelines',
            'countFailStudents','countPassStudents','countPendingStudents','countDoneStudents',
            'countCancelStudents','companyTopRecruitment'));
       }catch (\Exception $ex) {
            DB::rollBack();
            abort(404);
        }
    }
}

app/Http/Controllers/Manager/SemesterController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Models\Timeline;
use App\Models\Semester;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\Manager\SemesterCreateRequest;
use App\Http\Requests\Manager\SemesterUpdateRepuest;
use App\Models\ModelControllers\SemesterModel;
use App\Supports\Log;

class SemesterController extends Controller
{
    public function index()
    {
        try {
            $semesters = Semester::all();
            return view('manager.semester.index', compact('semesters'));
        } catch (\Exception $ex) {
            DB::rollBack();
            abort(404);
        }
    }

    public function create()
    {
        try {
            return view('manager.semester.createSemester');
        } catch (\Exception $ex) {
            DB::rollBack();
            abort(404);
        }
    }

    public function store(SemesterCreateRequest $request)
    {
        try {
            $input = $request->all();
            $semester = new SemesterModel;
            $newData = $semester->upsertSemester($input);
            Log::save('Nhóm Ngành', $request->method(), null, $newData);
            return redirect()->route('manager.semester.index')->with('success', 'Thêm Thành Công');
        } catch (\Exception $ex) {
            DB::rollback();
            abort(404);
        }
    }
    public function edit($id)
    {
        try {
            $semester = Semester::find($id);
            if (strtotime($semester->to) >= strtotime(date("Y-m-d H:i:s"))) {
                return view('manager.semester.editSemester', compact('semester'));
            } else {
                return redirect()->back()->with('fail', 'Các Kỳ đã qua không thể sửa');
            }
        } catch (\Exception $ex) {
            abort(404);
        }
    }

    public function update(SemesterUpdateRepuest $request, $id)
    {
        try {
            $input = $request->all();
            $input['id'] = $id;
            $semester = new SemesterModel;
            $semester->upsertSemester($input, true);
            return redirect()->route('manager.semester.index')->with('success', 'Đã Sửa Thành Công');
        } catch (\Exception $ex) {
            abort(404);
        }
    }

    public function destroy($id)
    {
        try {
            $timeLine = Timeline::where('semester_id', '=', $id)->where('deleted_at', NULL)->first();
            if ($timeLine) {
                $timeLine->delete();
            }
            $semester = Semester::find($id);
            $semester->delete();
            return redirect()->route('manager.semester.index')->with('success', 'Xóa thành công');
        } catch (\Exception $ex) {
            abort(404);
        };
    }
}

app/Http/Controllers/Manager/UserLogController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\UserLog;
use Illuminate\Support\Facades\DB;

class UserLogController extends Controller
{
    public function index()
    {
        try {
            $userLogs = UserLog::all()->sortByDesc("id");
            return view('manager.userLog.index', compact('userLogs'));
        } catch (\Exception $ex) {
            DB::rollBack();
            abort(404);
        }
    }
    public function getLogByUser($id)
    {
        try {
            $userLogs = UserLog::where('created_by', $id)->orderBy('id', 'desc')->get();
            return view('manager.userLog.index', compact('userLogs'));
        } catch (\Exception $ex) {
            DB::rollBack();
            abort(404);
        }
    }
}

resources/views/manager/semester/createSemester.blade.php
@extends('layouts.dashboard')
@section('page-title', 'Kỳ Học | Tạo mới')
@section('title', 'Trang quản trị')
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="/admin">Tổng Quan</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('manager.semester.index') }}">Danh Sách kỳ học</a>
                        </li>
                        <li class="breadcrumb-item active">Thêm kỳ học</li>
                    </ol>
                </div>
                <h4 class="page-title">Thêm kỳ học</h4>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card-box">
                <form method="POST"  onsubmit="getLoading()" action="{{ route('manager.semester.store') }}">
                    @csrf
                    @method('POST')
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Tên Kỳ học</label>
                        <div class="col-sm-10">
                            <div class="form-group has-muted bmd-form-group">
                                <input type="text" class="form-control" id="exampleInput3" name="name"
                                    value="{{ old('name') }}">
                                @error('name')
                                    <span class="text-danger small font-italic">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Mô tả</label>
                        <div class="col-sm-10">
                            <div class="form-group has-muted bmd-form-group">
                                <input type="text" class="form-control" id="exampleInput3" name="description"
                                    placeholder="Mô tả kỳ học" value="{{ old('description') }}">
                                @error('description')
                                    <span class="text-danger small font-italic">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Ngày bắt đầu kỳ mới</label>
                        <div class="col-sm-4">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <input type="date" class="form-control" name="from" value="{{ old('from') }}">
                                    @error('from')
                                        <span class="text-danger small font-italic">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>

                        </div>
                        <label class="col-sm-2 col-form-label">Ngày kết thúc kỳ</label>
                        <div class="col-sm-4">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <input type="date" class="form-control" name="to" value="{{ old('to') }}">
                                    @error('to')
                                        <span class="text-danger small font-italic">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>

                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Thêm giời gian thực tập</button>

                </form>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $a = document.getElementsByClassName('bmd-form-group').c
    </script>
@endsection

resources/views/manager/semester/editSemester.blade.php
@extends('layouts.dashboard')
@section('page-title', 'Kỳ Học | Tạo mới')
@section('title', 'Trang quản trị')
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="/admin">Tổng Quan</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('manager.semester.index') }}">Danh Sách kỳ học</a>
                        </li>
                        <li class="breadcrumb-item active">Chỉnh sửa kỳ học</li>
                    </ol>
                </div>
                <h4 class="page-title">Chỉnh sửa kỳ học</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card-box">
                <form method="POST"  onsubmit="getLoading()" action="{{ route('manager.semester.update', $semester->id) }}">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Tên kỳ học</label>
                        <div class="col-sm-10">
                            <div class="form-group has-muted bmd-form-group">
                                <label for="exampleInput3" class="bmd-label-floating">Tên kỳ học</label>
                                <input type="text" class="form-control" id="exampleInput3" name="name"
                                    value="{{ $semester->name }}">

                                @error('name')
                                    <span class="text-danger small font-italic">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Mô tả</label>
                        <div class="col-sm-10">
                            <div class="form-group has-muted bmd-form-group">
                                <input type="text" class="form-control" id="exampleInput3" name="description"
                                    placeholder="Mô tả kỳ học" value="{{ $semester->description }}">

                                @error('decription')
                                    <span class="text-danger small font-italic">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Ngày bắt đầu kỳ mới</label>
                        <div class="col-sm-4">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <input type="date" class="form-control" name="from"
                                        value="{{ date('Y-m-d', strtotime($semester->from)) }}">
                                    @error('from')
                                        <span class="text-danger small font-italic">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>

                        </div>
                        <label class="col-sm-2 col-form-label">Ngày kết thúc kỳ</label>
                        <div class="col-sm-4">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <input type="date" class="form-control" name="to"
                                        value="{{ date('Y-m-d', strtotime($semester->to)) }}">
                                    @error('to')
                                        <span class="text-danger small font-italic">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>

                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Chỉnh sửa</button>

                </form>
            </div>
        </div>
    </div>
@endsection

@section('script')

@endsection

resources/views/manager/semester/index.blade.php
@extends('layouts.dashboard')
@section('page-title', 'Quản lý kỳ học | Tổng quan')
@section('title', 'Quản lý kỳ học')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="/admin">Tổng Quan</a></li>
                    <li class="breadcrumb-item active">Danh sách kỳ học</li>
                </ol>
            </div>
            <h4 class="page-title">Danh sách kỳ học</h4>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card-box">
            <div class="table-responsive">
                <table id="datatable1" class="table">
                    <thead class=" text-primary">
                        <tr>
                            <th>#</th>
                            <th>Tên Kỳ</th>
                            <th>Băt Đầu Kỳ</th>
                            <th>Kết Thúc Kỳ</th>
                            <th>Mô Tả</th>
                            <th>Chức Năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($semesters as $key => $row)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $row->name }}</td>
                            <td>{{ date('d/m/Y', strtotime($row->from)) }}</td>
                            <td>{{ date('d/m/Y', strtotime($row->to)) }}</td>
                            <td>{{ $row->description }}</td>
                            <td class="td-actions ">
                                <div class="row text-center">
                                @if ($row->to >= now())
                                <a href="{{ route('manager.semester.edit', $row->id) }}" type="button" rel="tooltip" class="btn btn-outline-primary mr-1">
                                    <i class="fas fa-pencil-alt"></i>
                                </a>
                                @endif
                                <?php
                                if ($row->from <= now()) {
                                    $testTime = 0;
                                    $test = 1;
                                } else {
                                    $testTime = 1;
                                    if (isset($test)) {
                                        $testTime = 0;
                                        $test = null;
                                    }
                                }
                                ?>
                                @if ($testTime == 1) 
                              
                                 
                                    <a href="javascript: document.getElementById('deletedRow{{$row->id}}').submit();" onclick="return confirm('Bạn sẽ xóa luôn kỳ thực tập. bạn có chắc chắn không ?')" title="xóa">

                                        <button type="button" rel="tooltip" class="btn btn-outline-secondary">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </a>
                                    <form action="{{ route('manager.semester.destroy', $row->id) }}" method="POST" id="deletedRow{{$row->id}}" class="d-none">
                                        @method('DELETE')
                                        @csrf
                                    </form>

                                </div>
                                @endif
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
@push('css')
<!-- third party css -->
<link href="assets/libs/datatables/dataTables.bootstrap4.css" rel="stylesheet" type="text/css" />
<link href="assets/libs/datatables/buttons.bootstrap4.css" rel="stylesheet" type="text/css" />
<link href="assets/libs/datatables/responsive.bootstrap4.css" rel="stylesheet" type="text/css" />
@endpush
@push('script')
<script src="assets/libs/datatables/jquery.dataTables.min.js"></script>
<script src="assets/libs/datatables/dataTables.bootstrap4.min.js"></script>
<!-- Buttons examples -->
<script src="assets/libs/datatables/dataTables.buttons.min.js"></script>
<script src="assets/libs/datatables/buttons.bootstrap4.min.js"></script>
<script src="assets/libs/jszip/jszip.min.js"></script>
<script src="assets/libs/pdfmake/pdfmake.min.js"></script>
<script src="assets/libs/pdfmake/vfs_fonts.js"></script>
<script src="assets/libs/datatables/buttons.html5.min.js"></script>
<script src="assets/libs/datatables/buttons.print.min.js"></script> b
<!-- Responsive examples -->
<script src="assets/libs/datatables/dataTables.responsive.min.js"></script>
<script src="assets/libs/datatables/responsive.bootstrap4.min.js"></script>
<script>
    $(document).ready(function() {
        $("#datatable1").DataTable({
            'aoColumnDefs': [{
                'bSortable': false,
                'aTargets': [-1] /* 1st one, start by the right */
            }],
            lengthChange: !1,
            buttons: ["copy", "excel"]
        }).buttons().container().appendTo("#datatable1_wrapper .col-md-6:eq(0)")
    });
</script>
@endpush